# Generated by Django 4.2.1 on 2023-10-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_delete', models.DateTimeField(auto_now_add=True)),
                ('microservice_auth_id', models.UUIDField(unique=True, verbose_name='Глобальный ID удалённого пользователя')),
                ('step', models.IntegerField(choices=[('marked', 1), ('deleted', 2)], default=1)),
            ],
        ),
    ]
