# Generated by Django 4.2.1 on 2023-11-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_deletedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
