# Generated by Django 4.2.1 on 2024-04-04 22:26

import auth_service.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_temptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=150, validators=[auth_service.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['username'], name='auth_user_username'),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['first_name'], name='auth_user_first_name'),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['last_name'], name='auth_user_last_name'),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['email'], name='auth_user_email'),
        ),
    ]
